[package]
name = "NES_Emulator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
miniquad = { version = "=0.4.0-alpha.10", features = ["log-impl"] }
